// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// User roles available in the application.
type Role struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Application user accounts.
type User struct {
	ID         int32              `json:"id"`
	Email      string             `json:"email"`
	Password   string             `json:"password"`
	FirstName  pgtype.Text        `json:"first_name"`
	LastName   pgtype.Text        `json:"last_name"`
	IsVerified bool               `json:"is_verified"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Mapping table for users and their assigned roles.
type UserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}
