// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	AssignDefaultRole(ctx context.Context, arg AssignDefaultRoleParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteUser(ctx context.Context, id int32) (int64, error)
	FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
}

var _ Querier = (*Queries)(nil)
