// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignDefaultRole = `-- name: AssignDefaultRole :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, id
FROM roles
WHERE name = $2
`

type AssignDefaultRoleParams struct {
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) AssignDefaultRole(ctx context.Context, arg AssignDefaultRoleParams) error {
	_, err := q.db.Exec(ctx, assignDefaultRole, arg.UserID, arg.Name)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password, first_name, last_name, is_verified)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at
`

type CreateUserParams struct {
	Email      string      `json:"email"`
	Password   string      `json:"password"`
	FirstName  pgtype.Text `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	IsVerified bool        `json:"is_verified"`
}

type CreateUserRow struct {
	ID        int32              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.IsVerified,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE
FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT u.id, u.email, u.password,
       COALESCE(u.first_name, '')::text AS first_name,
       COALESCE(u.last_name, '')::text  AS last_name,
       u.is_verified, u.created_at, u.updated_at,
       COALESCE(array_agg(r.name) FILTER (WHERE r.name IS NOT NULL), '{}')::text[] AS roles
FROM users u
         LEFT JOIN user_roles ur ON ur.user_id = u.id
         LEFT JOIN roles r ON r.id = ur.role_id
WHERE u.email = $1
GROUP BY u.id
`

type FindUserByEmailRow struct {
	ID         int32              `json:"id"`
	Email      string             `json:"email"`
	Password   string             `json:"password"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	IsVerified bool               `json:"is_verified"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Roles      []string           `json:"roles"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.password,
       COALESCE(u.first_name, '')::text AS first_name,
       COALESCE(u.last_name, '')::text  AS last_name,
       u.is_verified, u.created_at, u.updated_at,
       COALESCE(array_agg(r.name) FILTER (WHERE r.name IS NOT NULL), '{}')::text[] AS roles
FROM users u
         LEFT JOIN user_roles ur ON ur.user_id = u.id
         LEFT JOIN roles r ON r.id = ur.role_id
GROUP BY u.id
ORDER BY u.id
`

type ListUsersRow struct {
	ID         int32              `json:"id"`
	Email      string             `json:"email"`
	Password   string             `json:"password"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	IsVerified bool               `json:"is_verified"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Roles      []string           `json:"roles"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
