http:
  routers:
    app:
      rule: Host(`api.gobooking.local`)
      entryPoints:
        - web
        - websecure
      service: app
      tls: { }

    mailpit:
      rule: Host(`mail.gobooking.local`)
      entryPoints:
        - web
        - websecure
      service: mailpit
      tls: { }

    adminer:
      rule: Host(`db.gobooking.local`)
      entryPoints:
        - websecure
      service: adminer
      tls: { }

  services:
    app:
      loadBalancer:
        servers:
          - url: http://app:8080

    mailpit:
      loadBalancer:
        servers:
          - url: http://mailpit:8025

    adminer:
      loadBalancer:
        servers:
          - url: http://adminer:8080

tls:
  certificates:
    - certFile: /certs/gobooking.local.pem
      keyFile: /certs/gobooking.local-key.pem
